server:
  port: 8081
  servlet:
    context-path: /lifamanagement



spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: hair
    password: hair1234
    url: jdbc:oracle:thin:@47.112.205.103:1521:orcl


mybatis:
  type-aliases-package: cn.edu.guet.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    cn.edu.guet.mapper: debug


